### ISSUE TITLE
Circular dependency in v3.0.0 prevents webhook from working

### ISSUE THREAD

**Issue by gtjoseph** [cla-assistant/cla-assistant#1044]
## URL to the linked Repository or Organization

https://github.com/
## Steps to reproduce the problem

1. Open a pull request
2.
3.

## What is the expected result?
The check shows status of CLA signature

## What happens instead?
The check shows:
`license/cla Expected — Waiting for status to be reported`
permanently

## Any other information? (attach screenshot if possible)
The server shows the following error:
```
(node:2108508) Warning: Accessing non-existent property 'get' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:787:11)
    at Object.get (node:internal/modules/cjs/loader:803:5)
    at RepoService.getPRCommitters (/usr/src/cla-assistant/cla-assistant/src/server/src/services/repo.js:365:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async updateStatusAndComment (/usr/src/cla-assistant/cla-assistant/src/server/src/webhooks/pull_request.js:67:28)
```

**Comment by gtjoseph** [comment]
A little more investigation shows that the issue is that src/server/src/services/webhook.js requires repo.js which in turn requires webhook.js.  repo.js also requires org.js which in turn also requires webhook.js.
