### ISSUE TITLE
Must specify two-factor authentication OTP code using GITHUB_TOKEN

### ISSUE THREAD

**Issue by hentisemmle** [cla-assistant/cla-assistant#356]
https://github.com/Semmle/cla-test

Steps to reproduce the problem:

1. Setup docker / mongo as per instructions. Created semmle-cla user for user/pass/token setup. 
2. Set env vars for HOST, PROTOCOL,GITHUB_CLIENT,\ 
    GITHUB_SECRET,GITHUB_USER,GITHUB_PASS,GITHUB_TOKEN,MONGODB
4. link repo
3. Create pull request 

What is the expected result?

cla assistant comments on the PR

What happens instead?

cla assistant errors as follows. 

```
{"name":"cla.semmle.com","hostname":"787acb5934ae","pid":16,"level":30,"msg":"✓ bootstrapped !!! App listening on cla.semmle.com:undefined","time":"2018-07-31T16:49:19.172Z","src":{"file":"/cla-assistant/src/server/app.js","line":195},"v":0}
pull request reopened https://github.com/Semmle/cla-test/pull/3
{"name":"cla.semmle.com","hostname":"787acb5934ae","pid":16,"level":50,"msg":"Error: {\"message\":\"Must specify two-factor authentication OTP code.\",\"documentation_url\":\"https://developer.github.com/v3/auth#working-with-two-factor-authentication\"}\n    at /cla-assistant/src/server/services/pullRequest.js:83:35\n    at collectData (/cla-assistant/src/server/services/github.js:118:21)\n    at /cla-assistant/src/server/services/github.js:34:13\n    at module.exports.__dirname.sendError (/cla-assistant/node_modules/github/lib/index.js:801:7)\n    at /cla-assistant/node_modules/github/lib/index.js:809:21\n    at callCallback (/cla-assistant/node_modules/github/lib/index.js:685:9)\n    at IncomingMessage.<anonymous> (/cla-assistant/node_modules/github/lib/index.js:749:13)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","time":"2018-07-31T16:52:46.476Z","src":{"file":"/cla-assistant/src/server/services/pullRequest.js","line":83},"v":0}
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Invalid URI "None"
    at Request.init (/cla-assistant/node_modules/request/request.js:273:31)
    at new Request (/cla-assistant/node_modules/request/request.js:127:8)
    at request (/cla-assistant/node_modules/request/index.js:53:10)
    at Function.post (/cla-assistant/node_modules/request/index.js:61:12)
    at BunyanSlack.write (/cla-assistant/node_modules/bunyan-slack/lib/bunyan-slack.js:70:10)
    at Logger._emit (/cla-assistant/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.error (/cla-assistant/node_modules/bunyan/lib/bunyan.js:1045:24)
    at /cla-assistant/src/server/services/pullRequest.js:83:29
    at collectData (/cla-assistant/src/server/services/github.js:118:21)
    at /cla-assistant/src/server/services/github.js:34:13
    at module.exports.__dirname.sendError (/cla-assistant/node_modules/github/lib/index.js:801:7)
    at /cla-assistant/node_modules/github/lib/index.js:809:21
    at callCallback (/cla-assistant/node_modules/github/lib/index.js:685:9)
    at IncomingMessage.<anonymous> (/cla-assistant/node_modules/github/lib/index.js:749:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cla-assistant@1.8.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cla-assistant@1.8.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cla-assistant/.npm/_logs/2018-07-31T16_52_46_512Z-debug.log

```

We thought this was because we're sending user/pass as well, so removed it, which resulted in 

```
{"name":"cla.semmle.com","hostname":"c5fdba3bd76f","pid":22,"level":30,"msg":"✓ bootstrapped !!! App listening on cla.semmle.com:undefined","time":"2018-07-31T16:58:49.571Z","src":{"file":"/cla-assistant/src/server/app.js","line":195},"v":0}
pull request reopened https://github.com/Semmle/cla-test/pull/4
/cla-assistant/node_modules/github/lib/index.js:339
      throw new Error('Basic authentication requires both a username and password to be set')
      ^
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cla-assistant@1.8.1~prestart: cla-assistant@1.8.1
6 info lifecycle cla-assistant@1.8.1~start: cla-assistant@1.8.1
7 verbose lifecycle cla-assistant@1.8.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle cla-assistant@1.8.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/cla-assistant/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle cla-assistant@1.8.1~start: CWD: /cla-assistant
10 silly lifecycle cla-assistant@1.8.1~start: Args: [ '-c', 'node app.js' ]
11 silly lifecycle cla-assistant@1.8.1~start: Returned: code: 1  signal: null
12 info lifecycle cla-assistant@1.8.1~start: Failed to exec start script
13 verbose stack Error: cla-assistant@1.8.1 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cla-assistant@1.8.1
15 verbose cwd /cla-assistant
16 verbose Linux 4.9.0-7-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error cla-assistant@1.8.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the cla-assistant@1.8.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
Unsure why this is happening.

**Comment by hentisemmle** [comment]
The solution is to use the GITHUB_TOKEN cvalue in GITHUB_PASS. 

The documentation is not very clear on having to do this if using a TOKEN. I suggest you update it.

**Comment by KharitonOff** [comment]
@hentisemmle I'm glad, that you could solve this issue! Would you mind to make a contribution to this project by updating our README correspondingly? I would really appreciate it!
