### ISSUE TITLE
Issues configuring stand-alone cla-assistant

### ISSUE THREAD

**Issue by ericnakagawa** [cla-assistant/cla-assistant#472]
URL to the linked Repo/Org: http://134.209.212.84:5000

Steps to reproduce the problem:

1. Click [Sign in with GitHub]
2. Note error.

Configuration, .env:
export PORT=5000
export PROTOCOL=http
export HOST=134.209.212.84
export MONGODB="mongo path, successfully "
export GITHUB_CLIENT=clientkey
export GITHUB_SECRET=clientsecret

export GITHUB_USER=botusername
export GITHUB_PASS=botpass

Github application settings:
Authorization callback URL: http://134.209.212.84:5000/auth/github/callback

What is the expected result?

The website and all assets load as expected identical to http://cla-assistant.io

I expect the GitHub auth process to begin.

What happens instead?

I receive an error.

```
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
    at Strategy.OAuth2Strategy.authenticate (/root/cla-assistant/node_modules/passport-oauth2/lib/strategy.js:137:25)
    at attempt (/root/cla-assistant/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/root/cla-assistant/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/root/cla-assistant/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/cla-assistant/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/cla-assistant/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/cla-assistant/node_modules/express/lib/router/layer.js:95:5)
    at /root/cla-assistant/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/cla-assistant/node_modules/express/lib/router/index.js:335:12)
    at next (/root/cla-assistant/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/cla-assistant/node_modules/express/lib/router/index.js:174:3)
    at router (/root/cla-assistant/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/cla-assistant/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/cla-assistant/node_modules/express/lib/router/index.js:317:13)
    at /root/cla-assistant/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/cla-assistant/node_modules/express/lib/router/index.js:335:12)
```

**Comment by doodeehee70** [comment]
ซ้ำของ #

**Comment by ericnakagawa** [comment]
@doodeehee70 Which #?

**Comment by ibakshay** [comment]
Hi @ericnakagawa,   Sorry for the late response. Are you able to configure the CLA Assistant now? (because you have closed the issue), If not I can help you configuring CLA Assistant :)

**Comment by ibakshay** [comment]
@ericnakagawa,  The previous reply which  I deleted is not from our team.
