### ISSUE TITLE
fail to run the application

### ISSUE THREAD

**Issue by zhangyangyu** [cla-assistant/cla-assistant#862]
## Steps to reproduce the problem

1. clone the default branch
2. follow Readme to try running the application, which way(npm start/docker run/docker compose) doesn't matter

## What is the expected result?

successfully running the application

## What happens instead?

fail to run the application, error:

```
ssertion failed: You must provide either mongoUrl|clientPromise|client in options
/home/ubuntu/cla-assistant/node_modules/connect-mongo/build/main/lib/MongoStore.js:119
            throw new Error('Cannot init client. Please provide correct options');
            ^

Error: Cannot init client. Please provide correct options
    at new MongoStore (/home/ubuntu/cla-assistant/node_modules/connect-mongo/build/main/lib/MongoStore.js:119:19)
    at Function.create (/home/ubuntu/cla-assistant/node_modules/connect-mongo/build/main/lib/MongoStore.js:136:16)
    at /home/ubuntu/cla-assistant/src/server/src/app.js:170:31
    at /home/ubuntu/cla-assistant/node_modules/async/dist/async.js:3638:28
    at replenish (/home/ubuntu/cla-assistant/node_modules/async/dist/async.js:443:21)
    at /home/ubuntu/cla-assistant/node_modules/async/dist/async.js:448:13
    at eachOfLimit$1 (/home/ubuntu/cla-assistant/node_modules/async/dist/async.js:474:34)
    at awaitable (/home/ubuntu/cla-assistant/node_modules/async/dist/async.js:211:32)
    at eachOfSeries (/home/ubuntu/cla-assistant/node_modules/async/dist/async.js:810:16)
    at awaitable (/home/ubuntu/cla-assistant/node_modules/async/dist/async.js:211:32)
```

**Comment by zhangyangyu** [comment]
It's my fault to use a malformed mongoUrl. But it's a pity the error is not obvious.

**Comment by Shegox** [comment]
@zhangyangyu good point and thanks for providing the solution. 

Let me reopen the issue to either:
- better document this
- or provide a better error message

**Comment by zhangyangyu** [comment]
Hmm, trying to catch the error for `mongoose.connect`. But strangely, either try to catch it in the callback or use `then/catch` works. Doesn't learn Node but doing a lot of search, all doing the same but the methods just not work. :(
