### ISSUE TITLE
appId option is required errors showing in the log

### ISSUE THREAD

**Issue by kwart** [cla-assistant/cla-assistant#980]
After upgrading from 2.10.0 to 2.13.0 we see a lot of error messages *"appId option is required"*  in the log.

```json
{
    "name": "cla.domain.name",
    "hostname": "ip-10-0-34-139.ec2.internal",
    "pid": 10138,
    "level": 50,
    "err": {
        "message": "[@octokit/auth-app] appId option is required",
        "name": "Error",
        "stack": "Error: [@octokit/auth-app] appId option is required\n    at createAppAuth (/home/ec2-user/cla-assistant/node_modules/@octokit/auth-app/dist-node/index.js:492:11)\n    at new Octokit (/home/ec2-user/cla-assistant/node_modules/@octokit/core/dist-node/index.js:113:20)\n    at new _a (/home/ec2-user/cla-assistant/node_modules/@octokit/core/dist-node/index.js:167:30)\n    at new OctokitWithDefaults (/home/ec2-user/cla-assistant/node_modules/@octokit/core/dist-node/index.js:147:9)\n    at new _a (/home/ec2-user/cla-assistant/node_modules/@octokit/core/dist-node/index.js:167:30)\n    at new OctokitWithDefaults (/home/ec2-user/cla-assistant/node_modules/@octokit/core/dist-node/index.js:147:9)\n    at getInstallationAccessToken (/home/ec2-user/cla-assistant/src/server/src/services/github.js:87:24)\n    at Object.callWithGitHubApp (/home/ec2-user/cla-assistant/src/server/src/services/github.js:137:33)\n    at createStatus (/home/ec2-user/cla-assistant/src/server/src/services/status.js:68:23)\n    at updateStatus (/home/ec2-user/cla-assistant/src/server/src/services/status.js:142:16)"
    },
    "msg": "[@octokit/auth-app] appId option is required",
    "time": "2023-03-08T17:39:05.177Z",
    "src": {
        "file": "/home/ec2-user/cla-assistant/src/server/src/services/github.js",
        "line": 141,
        "func": "callWithGitHubApp"
    },
    "v": 0,
    "req_id": "1e058fe0-bdd8-11ed-934e-7fc39d6f16b8"
}

```

I see the `appId` is only referenced in the `config.js` and takes env `GITHUB_APP_ID` as a value.
Still, the environment variable is neither mentioned in the `README.md` nor listed in `.env.example`. 

```bash
$ git grep appId
src/server/src/config.js:                appId: process.env.GITHUB_APP_ID,

$ git grep GITHUB_APP_ID
src/server/src/config.js:                appId: process.env.GITHUB_APP_ID,
```

Is the `GITHUB_APP_ID` mandatory now? If not, could you skip the problematic code where it's used?

**Comment by gtjoseph** [comment]
Not only are they showing in the logs, since Slack integration is implemented as a logger, they're also getting posted to the configured Slack channel.
Looks to be caused by commit 
0529ac3d42bd001917e701b479578418eb1c5caf
Add GitHub App as a hidden feature (#781)

This commit seems to add support for regular GutHub apps but breaks OAuth apps in the process.
